[package]
name = "garu-route"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
log = "0"
env_logger = "0"
icmp-socket = "0.2.0"
prettytable-rs = "0.10.0"
dns-lookup = "2.1.0"
curl = "0.4.49"
serde_json = "1.0.142"
